"""Framework-neutral application services."""

from watermark_removal_lab.application.batch import (
    BATCH_SCHEMA_VERSION,
    BatchCancellationReason,
    BatchContractError,
    BatchFailurePolicy,
    BatchItemError,
    BatchItemResult,
    BatchItemStatus,
    BatchMedia,
    BatchOperation,
    BatchPlan,
    BatchPreflightError,
    BatchSpec,
    BatchSummary,
    ImageBatchItemSpec,
    PlannedImageBatchItem,
    plan_batch,
)
from watermark_removal_lab.application.image_removal import (
    BoxMaskSource,
    ImageRemovalError,
    ImageRemovalInputError,
    ImageRemovalOutputError,
    ImageRemovalProcessingError,
    ImageRemovalRequest,
    ImageRemovalResult,
    ImageRemovalStatus,
    MaskFileSource,
    OverwritePolicy,
    build_failed_image_removal_result,
    remove_image,
)

__all__ = [
    "BATCH_SCHEMA_VERSION",
    "BatchCancellationReason",
    "BatchContractError",
    "BatchFailurePolicy",
    "BatchItemError",
    "BatchItemResult",
    "BatchItemStatus",
    "BatchMedia",
    "BatchOperation",
    "BatchPlan",
    "BatchPreflightError",
    "BatchSpec",
    "BatchSummary",
    "BoxMaskSource",
    "ImageBatchItemSpec",
    "ImageRemovalError",
    "ImageRemovalInputError",
    "ImageRemovalOutputError",
    "ImageRemovalProcessingError",
    "ImageRemovalRequest",
    "ImageRemovalResult",
    "ImageRemovalStatus",
    "MaskFileSource",
    "OverwritePolicy",
    "PlannedImageBatchItem",
    "build_failed_image_removal_result",
    "plan_batch",
    "remove_image",
]
